### ISSUE TITLE
Non-Blank Spaces Break Custom Styling

### ISSUE THREAD

**Issue by ghost** [leftstick/angular-number-picker#10]
Overall, seems like a great directive. However, when trying to customize styles, the nbsp; added to the markup for spacing around the controls makes custom styling very difficult. This should not be hardcoded into the generated markup, and should be left up to style implementations to customize this spacing around the controls.

**Comment by leftstick** [comment]
Can you try with latest version `2.0.1`?

**Comment by ghost** [comment]
@leftstick Worked like a charm. Thanks for the quick turn around!!
