### ISSUE TITLE
option or style to make singular / plural left or right of number

### ISSUE THREAD

**Issue by almothafar** [leftstick/angular-number-picker#11]
Hi, 

You done nice work with this directive, but I would like to add suggestion for this directive like what I wrote in the subject here, I think my title is simple, it will be nice if I can make plural  on the left or right of number, this can be done with attribute or at least in the template add value and plural  in different span with class so I can flip them using float.

**Comment by leftstick** [comment]
You mean, you would like to change the position of `singular`/`plural` string? By default, it's placed on the right of the number, you want to have an option to change this behavior？

**Comment by almothafar** [comment]
Yes, I mean on the right or left of number, as example if I placed $ dollar sign as `singular/plural` for the USA the currency must be left sign like $20 not 20$ 

Its enough just to change the template to apply the new attribute configuration or just wrape {{value}} with span having class, and {{singular/plural}} with another span with another span. and then I can make my custom style on the class.

**Comment by leftstick** [comment]
Try `2.1.0`, i've added `unitPosition` as new option to control where to place `singular/plural`. And new classes `picker-unit-left`, `picker-unit-right` were added for customizing the unit span

**Comment by almothafar** [comment]
Yes now its working :) and btw the new attribute must be in README is `unit-position`  not `unitPosition`.
And another notice, now there is no spacing between `singular/plural` and number, for me its OK, and this what I want, but not sure if the current users that installed this directive will be happy or not.

Finally, Nice work, thank you.

**Comment by leftstick** [comment]
Thanks for reminding
