### ISSUE TITLE
angular-number-picker in ng-repeat

### ISSUE THREAD

**Issue by Brhernann** [leftstick/angular-number-picker#16]
Hi, i have a simple question  how can i use it in ng-repeat?

I have a dynamic array with different elements and i can´t Assign a different `value` but  to be independent.

**Comment by leftstick** [comment]
Try not use value directly linked at `$scope`, but with the repeat data instead, as below:

```javascript
demo.controller('DemoController', ['$scope', function($scope) {
  
        $scope.items = [{
          label: 'shaver',
          num: 0
        },{
          label: 'oven',
          num: 0
        }];
}]);
```

```html
<div ng-repeat="item in items" class="item">
      <label for="">{{ item.label  }}</label>: <h-number value="item.num" min="0" max="10" step="1"></h-number>
</div>
```

Here is the [plunker](http://plnkr.co/edit/fXPSbp?p=preview)
