### ISSUE TITLE
Adding an ng-change

### ISSUE THREAD

**Issue by acedesigns** [leftstick/angular-number-picker#2]
Hey There Howard.
This more of a feature than a issue.

I was trying to do the following: pn my `Controller`

``` javascript
demo.controller('Demo', ['$scope', function($scope) {
   $scope.input = { num: 0 };
  $scope.NumberChanged = function () {
    alert( $scope.input.num );
  };
$scope.getNumber = function() {
     alert('The number is: [' + $scope.input.num + ']');
   };
}]);
```

My `Html`

``` html
<h-number 
    ng-change="NumberChanged()" 
    ng-model="number" 
    value="input.num" min="1" max="" step="1">
</h-number>
```

**Comment by leftstick** [comment]
Since `ng-change` requires the `ng-model` which i haven't used in my implementation. 
So i'd like to give a new attribute called `change` to fulfill your requirement.

It's done in version `1.2.0`, give a try, and welcome your comments
