### ISSUE TITLE
Change value

### ISSUE THREAD

**Issue by Shiftane** [leftstick/angular-number-picker#3]
Hi,
I have a question about your plugin.
I use it and I have a non update value in my change method. 

Check the code here

http://plnkr.co/edit/R6iz6jJUlHym7rQLU4MH?p=preview

Is that normal to have a different value as the one shown in the h-number ?

Thanks

**Comment by leftstick** [comment]
It's not correct, but a bug. Thanks for reporting this issue.

I just fixed it with a new version `1.2.2`, you can check my new [plunker](http://plnkr.co/edit/Aww1cb785mZIPqNHgZ4v?p=preview)

**Comment by leftstick** [comment]
It's not correct, but a bug. Thanks for reporting this issue.

I just fixed it with a new version `1.2.2`, you can check my new [plunker](http://plnkr.co/edit/Aww1cb785mZIPqNHgZ4v?p=preview)
