### ISSUE TITLE
Write in input

### ISSUE THREAD

**Issue by Seiifer** [leftstick/angular-number-picker#4]
IS there a way to write directly in the input as well, so I can type my own value and then keep changing it using the buttons ?

**Comment by Seiifer** [comment]
This is actually not closed.

**Comment by leftstick** [comment]
Unfortunately, i haven't implemented such a feature, would you like to give me a PR on this?

**Comment by Seiifer** [comment]
Well, when I'll get some time I'll try to look into it, but do not expect too much tbh.
