### ISSUE TITLE
Incorrect step on single click

### ISSUE THREAD

**Issue by Trylar** [leftstick/angular-number-picker#6]
I have Ionic application and this directive works strange for me. On long tap step is correct, but on single short tap it doubles.

I found it happens because two events are fired: 'touchend' and 'click'.

**Comment by leftstick** [comment]
Since i `preventDefault` while `touchstart` is triggered, `click` should never be called in touchable device.

Can you provide snippet or plunker of your case?

**Comment by Trylar** [comment]
Thanks for response, this is plunker http://plnkr.co/edit/bKIHWX53QsqvOSxa7mfB?p=preview
To reproduce behavior you should turn on device mode.

**Comment by leftstick** [comment]
Seems that `ionic` will trigger `touchend` event one more time, which i have no idea why is that!

But i have a quick fix on this in my side. You can try the latest version
