### ISSUE TITLE
Max is not respected if step multiple can exceed max

### ISSUE THREAD

**Issue by jdcaballerov** [leftstick/angular-number-picker#9]
I think the value must be coerced to max if adding a step exceeds max. For instance try the demo as:

```
                        <h-number change="onChanged()" value="input.num" singular="car" plural="cars" min="1" max="10" step="2"></h-number>
```

one can notice that the counter can reach 11.

best,

**Comment by leftstick** [comment]
Thanks for reporting this issue, fixed.
